main:
  - name: "Home"
    url: "/"
    weight: 1

  - name: "Publications"
    url: "/publications/"
    weight: 2

  - name: "Conferences"
    url: "/conferences/"
    weight: 3

  - name: "Awards"
    url: "/awards/"
    weight: 4

  - name: "Media"
    url: "/media/"
    weight: 5
